definitions:
  gopitman.Essay:
    properties:
      address:
        type: string
      code_object:
        type: string
      coordinates:
        type: string
      descriptions:
        type: string
      title:
        type: string
    type: object
  gopitman.User:
    properties:
      name:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - name
    - password
    - username
    type: object
  handler.sigInInput:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
info:
  contact: {}
paths:
  /api/v1/essay:
    post:
      consumes:
      - application/json
      description: create essay
      operationId: create-essay
      parameters:
      - description: create essay
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/gopitman.Essay'
      produces:
      - application/json
      responses: {}
      summary: Create Essay
      tags:
      - essay
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: Auth token
      operationId: aunhetication
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.sigInInput'
      produces:
      - application/json
      responses: {}
      summary: SignIn
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: create account
      operationId: create-account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/gopitman.User'
      produces:
      - application/json
      responses: {}
      summary: SignUp
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
